name: build_stm32

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build_STM32F407IGHx:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.8.1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure CMake
        run: cmake ${{github.workspace}}/stm32_firmware -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -B${{github.workspace}}/build -G "Unix Makefiles"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target ci