name: build_ros2

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: humble
            docker_image: osrf/ros:humble-desktop
          - ros_distro: iron
            docker_image: osrf/ros:iron-desktop
          - ros_distro: jazzy
            docker_image: osrf/ros:jazzy-desktop
          - ros_distro: rolling
            docker_image: osrf/ros:rolling-desktop

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Build
        shell: bash
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.sh
          cd ${{github.workspace}}/ros2_driver
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}